//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanVali.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class tChiTietSanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tChiTietSanPham()
        {
            this.tChiTietHDBs = new HashSet<tChiTietHDB>();
        }
    
        public int MaChiTietSP { get; set; }
        public string TenChiTietSP { get; set; }
        public Nullable<int> MaDM { get; set; }
        public Nullable<double> DonGiaBan { get; set; }
        public Nullable<double> GiamGia { get; set; }
        public Nullable<int> SLTon { get; set; }
        public string KichThuoc { get; set; }
        public string MauSac { get; set; }
        public string AnhDaiDien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tChiTietHDB> tChiTietHDBs { get; set; }
        public virtual tDanhMucSP tDanhMucSP { get; set; }
        [NotMapped]
        public HttpPostedFile AnhDaiDienFile { get; set; }
    }
}
