//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanVali.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLBanVaLiEntities : DbContext
    {
        public QLBanVaLiEntities()
            : base("name=QLBanVaLiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tChiTietHDB> tChiTietHDBs { get; set; }
        public virtual DbSet<tChiTietSanPham> tChiTietSanPhams { get; set; }
        public virtual DbSet<tDanhMucSP> tDanhMucSPs { get; set; }
        public virtual DbSet<tHoaDonBan> tHoaDonBans { get; set; }
        public virtual DbSet<tKhachHang> tKhachHangs { get; set; }
    }
}
